GET http://localhost:3001/todos


###
POST  http://localhost:3001/todo/new
Content-Type: application/json

{
    "text" : "third task",
    "desc": "Some informatin about this, this task is very imp"

}

###
DELETE  http://localhost:3001/todo/delete/645201fc5e2a46aa1c71b369

###
DELETE  http://localhost:3001/todos/delete

###
PUT http://localhost:3001/todo/edit/6446c1428b7afd4569ed56b5
Content-Type: application/json

{
    "text": "new title",
    "desc": "workinggggg????",
    "tags": [{"tagName":"Worki", "color":"white"}]
}