GET http://localhost:3001/todos


###
POST  http://localhost:3001/todo/new
Content-Type: application/json

{
    "text" : "second task"
}

###
DELETE  http://localhost:3001/todo/delete/6446c1668b7afd4569ed56b8

###
PUT http://localhost:3001/todo/edit/6446c1428b7afd4569ed56b5
Content-Type: application/json

{
    "text": "updated again"
}